### ISSUE TITLE
FR: ability to configure scopes where copilot is disabled

### ISSUE THREAD

**Issue by jkohlin** [jamesonknutson/disable-copilot-comment-completions#1]
Hi and thanks for the nice plugin. However, I wonder if it would be possible to add a configuration array where we can specify what scopes we want copilot disabled?
Thanks!

**Comment by jamesonknutson** [comment]
Hi there, sure, this isn't too hard to implement. I'll find some time in the next few days to add this and reply here once done.

**Comment by jkohlin** [comment]
That would be awesome!!

**Comment by jkohlin** [comment]
perhaps I can contribute? 
I've forked the repo, but how do I get VS code to recognize the workspace as an extension so that I can debug it?

**Comment by jamesonknutson** [comment]
[Added in latest update :)](https://github.com/jamesonknutson/disable-copilot-comment-completions/releases/tag/v1.0.1)

Should be live on the Marketplace whenever Microsoft gets off their butts and processes the changes. Enjoy!
